config/routes.rb
Rails.application.routes.draw do
  get "font_test/index"
  get "button_test/index"
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get 'button_test', to: 'button_test#index'
  get 'font_test', to: 'font_test#index'

  # Nested resources
  resources :users do
    resources :clinics
  end

  resources :clinics, only: [:index, :show, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  resources :pets

  resources :bookings, except: [:new, :create] do
    resource :review, only: %i[new create edit update destroy]
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :species, presence: true,
                    inclusion: { in: ['cat', 'dog', 'bird', 'small mammal', 'reptile/amphibian', 'farm animal', 'horse', 'fish', 'other/exotic'],
                                 message: "%<value>s is not a valid species, must be one of: cat, dog, bird, small mammal, reptile/amphibian, farm animal, horse, fish, or other/exotic" }
  # validates :breed, presence: true, length: { minimum: 2, maximum: 50 }
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :weight, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
  has_many :bookings, dependent: :destroy
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = current_user.pets
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = current_user.pets.build(pet_params) # This associates the pet with the logged-in user
    if @pet.save
      redirect_to @pet, notice: 'Pet was successfully created.', allow_other_host: true
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to @pet
    else
      render :edit
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path, notice: 'Pet was successfully deleted.'
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :breed, :weight, :description, :photo)
  end
end

app/views/pets/_form.html.erb
<%= form_with model: @pet, local: true do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :species %><br>
    <%= f.select :species, %w[cat dog bird rabbit exotic]%>
  </p>
    <p>
    <%= f.label :breed  %><br>
    <%= f.text_field :breed %>
  </p>
  <p>
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </p>
  <% if @pet.photo.attached? %>
  <p>Current Photo:</p>
  <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

<p>
  <%= f.label :photo %><br>
  <%= f.file_field :photo %>
</p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<%= render 'form', pet: @pet %>

<div class= "mt-5">
<%= link_to '← Back', pet_path(@pet), class: 'btn btn-outline-secondary' %>
</div>

app/views/pets/index.html.erb
<div class="container mt-4">
  <h1 class="mb-3 text-center"><strong>My Pets</strong> <i class="fa-solid fa-paw"></i></h1>
  <div class="boundary"></div>
  <div class="row <%= @pets.size % 3 == 0 ? '' : 'justify-content-center' %>">
    <% @pets.each do |pet| %>
      <div class="col-md-6 col-lg-4 mb-4">
        <%= link_to pet_path(pet), class: "text-decoration-none" do %>
          <div class="pets-card-container py-3 px-2 text-center">
            <div class="pets-card">
              <div class="pets-image-container mb-3">
                <% if pet.photo.attached? %>
                  <%= cl_image_tag pet.photo.key, alt: 'Pet image', class: 'img-fluid pet-image' %>
                <% else %>
                  <%= image_tag 'pets.png', alt: 'Pet image', class: 'img-fluid pet-image' %>
                <% end %>
              </div>
              <p class="mb-0"><strong><%= pet.name %></strong></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-start text-center mt-5">
    <%= link_to '← Back', root_path, class: "btn btn-outline-secondary" %>
</div>

app/views/pets/new.html.erb
<h1>Add a new pet</h1>

<% if @pet.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
    <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @pet, local: true, data: { turbo: false } do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :species %><br>
    <%= f.select :species, ['cat', 'dog', 'bird', 'small mammal', 'reptile/amphibian', 'farm animal', 'horse', 'fish', 'other/exotic'] %>
  </p>
    <p>
    <%= f.label :breed %> (optional)<br>
    <%= f.text_field :breed %>
  </p>
  <p>
    <%= f.label :weight %> (kg)<br>
    <%= f.number_field :weight, min: 0 %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :age %> (years)<br>
    <%= f.number_field :age, min: 0 %>
  </p>
    <p>
    <%= f.label :photo %><br>
    <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit "Add Pet", class: "btn btn-primary" %>
  </p>
<% end %>

<div class= "mt-5">
<%= link_to '← Back', request.referer || root_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/pets/show.html.erb
<div class="container mt-4">
  <h1 class="mb-3 text-center"><strong><%= @pet.name %></strong></h1>
  <div class="boundary"></div>
  <div class="row">
    <div class="col-12 mb-4 d-flex align-items-center justify-content-center">
      <div class="pet-card-container p-3">
        <div class="pet-card">
          <div class="pets-image-container">
            <% if @pet.photo.attached? %>
              <%= cl_image_tag @pet.photo.key, alt: 'Pet image', class: 'img-fluid pet-image' %>
            <% else %>
              <%= image_tag 'pets.png', alt: 'Pet image', class: 'img-fluid pet-image' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 mb-4 px-4">
      <div class="pet-card-details text-center">
        <div class="pet-stats row">

          <div class="col-6 col-md-6 mb-3 mb-md-0" id="pet-list-left">
            <ul class="pet-list text-left">
              <li><b>Species</b>: <%= @pet.species %></li>
              <li><b>Age</b>: <%= pluralize(@pet.age, 'year') %> old</li>
            </ul>
          </div>

          <div class="col-6 col-md-6" id="pet-list-right">
            <ul class="pet-list text-left">
              <li><b>Breed</b>: <%= @pet.breed.blank? ? "N/A" : @pet.breed %></li>
              <li><b>Weight</b>: <%= @pet.weight %> kg</li>
            </ul>
          </div>

          <div class="col-12" id="pet-description">
            <p><b>Pet description</b>: <em><%= @pet.description %></em></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 mb-4">
      <% if @pet.bookings.any? %>
        <div class="boundary"></div>
        <h2 class="mb-4">Appointments for your pet</h2>
        <div class="table-responsive bg-light">
          <table class="table table-striped">
            <thead class="table-success">
              <tr>
                <th>Pet</th> <!-- New column for pet image -->
                <th>Date</th>
                <th>Time</th>
                <th class="d-none d-sm-table-cell">Description</th>
                <th class="d-none d-sm-table-cell">Clinic</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @pet.bookings.each do |booking| %>
                <tr>
                  <!-- Pet Image and Name Column with Link -->
                  <td class="text-center ">
                    <%= link_to pet_path(booking.pet), class: "text-decoration-none" do %>
                      <% if booking.pet&.photo&.attached? %>
                        <%= cl_image_tag booking.pet.photo.key, alt: 'Pet image', class: 'img-thumbnail rounded-circle', style: 'width: 60px; height: 60px;' %>
                      <% else %>
                        <%= image_tag 'pets.png', alt: 'Pet image', class: 'img-thumbnail rounded-circle', style: 'width: 60px; height: 60px;' %>
                      <% end %>
                      <div class="pet-name mt-0"><%= booking.pet.name %></div>
                    <% end %>
                  </td>
                  <td><%= booking.date %></td>
                  <td><%= booking.time.strftime("%I:%M %p") %></td>
                  <td class="d-none d-sm-table-cell"><%= booking.description %></td>
                  <td class="d-none d-sm-table-cell"><%= booking.clinic.email if booking.clinic %></td>
                  <td class="text-center">
                    <%= link_to "Show", booking_path(booking), class: "btn btn-primary btn-sm text-white" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
    <div class="col-12 d-flex justify-content-space-between">
      <% if current_user.pets.include?(@pet) %>
        <div class="col-6 text-center">
          <%= link_to edit_pet_path(@pet), class: "pet-link" do %>
            <i class="fa-solid fa-pen-to-square"></i> Edit pet
          <% end %>
        </div>

        <div class="col-6 text-center">
          <%= button_to pet_path(@pet), method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this pet?' } do %>
            <i class="fa-solid fa-trash"></i> Remove pet
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="back-link mt-5">
  <%= link_to "← Back", pets_path, class: "btn btn-outline-secondary" %>
</div>