config/routes.rb
Rails.application.routes.draw do
  get "font_test/index"
  get "button_test/index"
  devise_for :users
  root to: "pages#home"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get 'button_test', to: 'button_test#index'
  get 'font_test', to: 'font_test#index'

  # Nested resources
  resources :users do
    resources :clinics
  end

  resources :clinics, only: [:index, :show, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end

  resources :pets

  resources :bookings, except: [:new, :create] do
    resource :review, only: %i[new create edit update destroy]
  end
end

app/views/shared/_filters.html.erb
<div class="container" id="new-filter-container">
  <div class="row">
    <div class="col-12">
      <div class="dropdown d-flex align-items-center">
        <a href="#" class="btn btn-primary dropdown-toggle" id="filterDropdown" data-bs-toggle="dropdown" aria-expanded="false">
          Filter Options
        </a>
        <div class="dropdown-menu dropdown-menu-end p-3 custom-dropdown-menu" aria-labelledby="filterDropdown">
          <%= form_with url: root_path, method: :get, local: true do %>
            <!-- Responsive Row for Filters -->
            <div class="row">
              <!-- Species Filter -->
              <div class="col-md-6 col-12 mb-3">
                <div class="form-group text-start">
                  <%= label_tag :species, class: "form-label text-primary-green d-block" do %>
                    <i class="fa-solid fa-paw me-2"></i> Species
                  <% end %>
                  <%= select_tag :species,
                        options_for_select(['All'] + Clinic.pluck(:species).flatten.uniq, params[:species]),
                        class: "form-control form-select filter-select",
                        multiple: true %>
                </div>
              </div>

              <!-- Care Type Filter -->
              <div class="col-md-6 col-12 mb-3">
                <div class="form-group text-start">
                  <%= label_tag :care_type, class: "form-label text-primary-green d-block" do %>
                    <i class="fa-solid fa-stethoscope me-2"></i> Care Type
                  <% end %>
                  <%= select_tag :care_type,
                        options_for_select(['All'] + Clinic.pluck(:care_type).flatten.uniq, params[:care_type]),
                        class: "form-control form-select filter-select",
                        multiple: true %>
                </div>
              </div>
            </div>

            <!-- Buttons -->
            <div class="d-flex flex-column flex-md-row justify-content-center gap-3 mt-3">
              <%= submit_tag "Filter", class: "btn btn-primary" %>
              <%= link_to "Reset", root_path, class: "btn btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer mt-5">
  <div class="footer-bottom">
    <p> <strong class="highlight">&copy; 2024 MEDIVET </strong> - Crafting Code, Delivering Excellence. All Rights Reserved</p>
    <p>
      <a href="#">Privacy Policy</a> | <a href="#">Terms and Conditions</a>
    </p>
    <div class="social-icons">
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
  </div>
</footer>

app/views/shared/_header_navbar.erb
<div class="navbar navbar-expand-xl navbar-light navbar-medivet sticky-top">
  <div class="container-fluid">

    <!-- Logo linking to homepage -->
      <%= link_to root_path, class: "navbar-brand d-none d-md-block" do %>
        <%= image_tag "medivet_logo.png", alt: "Medivet Logo" %>
      <% end %>

<% if !current_user || (current_user && current_user.role.nil?) || (current_user && !current_user.vet?) %>
  <%= render partial: "shared/searchbar" %>
<% end %>


    <!-- Navbar Toggler for Mobile View -->

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Right section: Navbar Links and User Menu -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto align-items-center"> <!-- align-items-center for vertical alignment -->
        <% if user_signed_in? %>
          <li class="nav-item mx-4 d-md-none">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item mx-4">
            <%= link_to "My Appointments", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item mx-4">
            <%= link_to "My Pets", pets_path, class: "nav-link" %>
          </li>
          <!-- <li class="nav-item mx-4">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li> -->

          <!-- Profile Dropdown with Dropdown Arrow on Left Side -->
          <li class="nav-item dropdown d-flex align-items-center flex-column align-items-md-end">
            <a href="#" class="nav-link d-flex align-items-center" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-chevron-down me-2"></i> <!-- Dropdown arrow icon on the left -->
                <span class="profile-text me-2"><%= current_user.first_name.present? ? "#{current_user.first_name}" : "User" %></span>
              <%= image_tag "https://media.licdn.com/dms/image/v2/C4E03AQHvlG-890y2gg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1552361570686?e=1737590400&v=beta&t=h0tD3X6_HT9lx39t-UU5m-fo4wDrg_VU6-TAFLjYxnk", class: "avatar", alt: "User Avatar" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end w-100 w-md-auto custom-dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to user_path(current_user), class: "dropdown-item" do %>
                <i class="fas fa-user"></i> My account
              <% end %>
              <%#= link_to new_user_clinic_path(current_user), class: "dropdown-item" do %>
                <%# <i class="fa-solid fa-house-chimney-medical"></i> Add a clinic %>
              <%# end %>
              <%= link_to new_pet_path, class: "dropdown-item" do %>
                <i class="fa-solid fa-paw"></i> Add a pet
              <% end %>
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </div>
          </li>
        <% else %>
         <!-- "Sign Up as a Vet" Button -->
         <div class="mt-3 mt-md-2 mt-lg-0 d-flex flex-column flex-md-row align-items-center">
             <li class="nav-item mx-4 d-md-none">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item mx-4 w-100">
              <%= link_to "Are you a veterinary professional?", new_user_session_path, class: "btn btn-on-primary w-100" %>
            </li>
            <li class="nav-item d-flex justify-content-center">
              <%= link_to "Customer Login", new_user_session_path, class: "nav-link text-md-center" %>
            </li>
         </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header_navbar_vet.html.erb
<div class="navbar navbar-expand-xl navbar-light navbar-medivet sticky-top">
  <div class="container-fluid">

    <!-- Logo linking to homepage -->
      <%= link_to root_path, class: "navbar-brand d-none d-md-block" do %>
        <%= image_tag "medivet_logo.png", alt: "Medivet Logo" %>
      <% end %>

    <!-- Navbar Toggler for Mobile View -->

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Right section: Navbar Links and User Menu -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto align-items-center"> <!-- align-items-center for vertical alignment -->
        <% if user_signed_in? %>
          <li class="nav-item mx-4 d-md-none">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item mx-4">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>

  <li class="nav-item mx-4">
  <% if @current_user_clinics.any? && @current_user_clinics.first.try(:id).present? %>
    <%= link_to "My Clinic", user_clinic_path(current_user, @current_user_clinics.first.id), class: "nav-link" %>
  <% else %>
    <%= link_to "Create a Clinic", new_user_clinic_path(current_user), class: "nav-link" %>
  <% end %>
</li>


          <!--<li class="nav-item mx-4">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li> -->

          <!-- Profile Dropdown with Dropdown Arrow on Left Side -->
          <li class="nav-item dropdown d-flex align-items-center flex-column align-items-md-end">
            <a href="#" class="nav-link d-flex align-items-center" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-chevron-down me-2"></i> <!-- Dropdown arrow icon on the left -->
              <span class="profile-text me-2">user name</span> <!-- Display user's name -->
              <%= image_tag "https://media.licdn.com/dms/image/v2/C4E03AQHvlG-890y2gg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1552361570686?e=1737590400&v=beta&t=h0tD3X6_HT9lx39t-UU5m-fo4wDrg_VU6-TAFLjYxnk", class: "avatar", alt: "User Avatar" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end w-100 w-md-auto custom-dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to user_path(current_user), class: "dropdown-item" do %>
                <i class="fas fa-user"></i> My account
              <% end %>
              <%= link_to new_user_clinic_path(current_user), class: "dropdown-item" do %>
                <i class="fa-solid fa-house-chimney-medical"></i> Add a clinic
              <% end %>
              <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </div>
          </li>
        <% else %>
        <!-- "Sign Up as a Pet parent" Button -->
        <div class="mt-3 mt-md-2 mt-lg-0 d-flex flex-column flex-md-row align-items-center">
            <li class="nav-item mx-4 d-md-none">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item mx-4 w-100">
              <%= link_to "Are you a pet parent?", "#", class: "btn btn-on-secondary w-100" %>
            </li>
            <li class="nav-item d-flex justify-content-center">
              <%= link_to "Customer Login", new_user_session_path, class: "nav-link text-md-center" %>
            </li>
        </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_vet_card.html.erb
<div class="vet-card card shadow-sm border-0 p-3 h-100">
  <!-- Full Width Top Section with Green Background -->
    <div <% if current_user.role == "vet" %>class="vet-card-header light-blue text-center p-4"<% else %>class="vet-card-header text-center p-4"<% end %>>
    <div class="vet-image mb-3">
      <% if clinic.image.attached? %>
        <%= cl_image_tag clinic.image.key, alt: 'Vet Image', class: 'img-fluid vet-profile-img' %>
      <% else %>
        <%= image_tag 'clinic.png', alt: 'Vet Image', class: 'img-fluid vet-profile-img' %>
      <% end %>
    </div>
    <h5 class="card-title text-white"><strong><%= clinic.clinic_name %></strong></h5>
  </div>


<!-- Rating Section -->
<div class="rating d-flex justify-content-center mt-4 align-items-center">
  <% rounded_rating = (clinic.average_rating + 0.2).floor %>
  <% 5.times do |i| %>
    <% if i < rounded_rating %>
      <i class="fas fa-star text-warning"></i>
    <% else %>
      <i class="far fa-star text-warning"></i>
    <% end %>
  <% end %>
  <span class="ms-2 text-muted">
    <strong><%= clinic.average_rating.round(1) %></strong>
    (<%= rand(5..102) %>)
  </span>
</div>


  <!-- Information Section -->
  <div class="info-box w-100 mt-4">
    <div class="d-flex mb-2">
      <i class="fas fa-map-marker-alt text-success me-2"></i>
      <span class="text-muted"><%= clinic.address %></span>
    </div>
    <div class="d-flex mb-2">
      <i class="fas fa-paw text-success me-2"></i>
      <span class="text-muted"><%= clinic.species.map { |species| species.split('/').map { |s| s.split.map(&:capitalize).join(' ') }.join('/').pluralize }.join(", ") %></span>
    </div>
  </div>

  <!-- View Profile Button -->
  <div class="text-center mt-3">
    <%= link_to 'View Profile', clinic_path(clinic), class: 'btn-primary w-75 mt-3' %>
  </div>
</div>